[project]
name = "patientmatchreviewer"
version = "0.3.4.3"
description = "GUI to help user review possible patient matches."
authors = [
    { name = "Kevin J. Delaney", email = "kjdelaney@health.ucsd.edu"}
]
license = {file = 'LICENSE'}
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
dependencies = [
    "pandas==3.0.5",
]

[project.urls]
documentation = "https://github.com/DBMI/PatientMatchReviewer"
homepage = "https://github.com/DBMI/PatientMatchReviewer"
repository = "https://github.com/DBMI/PatientMatchReviewer"

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
argparse = "^1.4.0"
wxpython = "4.2.5"
pywin32 = "311"
pandas = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[project.scripts]
review_manual_matches = "patientmatchreviewer.__main__:main"

[tool.ruff]
# Target Python version
target-version = "py311"
# Only look at your specific source directory
src = ["src/patientmatchreviewer"]


[tool.setuptools]
# Automatically includes data files specified in MANIFEST.in
include-package-data = true
