import logging
from collections.abc import Callable as Callable
from configparser import ConfigParser

def ensure_path_possible(filename: str, log: logging.Logger) -> bool: ...
def get_base_path() -> str: ...
def get_config(log: logging.Logger, config_file: str = None) -> ConfigParser: ...
def get_exe_path(log: logging.Logger) -> str: ...
def get_exe_version(log: logging.Logger) -> str: ...
def get_logging_directory(suggested_dir: str) -> str | None: ...
def get_temp_directory() -> str | None: ...
def is_writable(pat_to_test: str) -> bool: ...
def __make_config(config_file: str, log: logging.Logger) -> None: ...
def parse_version_file() -> str: ...
def resource_path(relative_path: str) -> str: ...
def write_config(
    config: ConfigParser, log: logging.Logger, config_file: str = ""
) -> None: ...
