import logging
from configparser import ConfigParser
from pathlib import Path

import pandas
import wx
import wx.adv

from patientmatchreviewer.wobbler import MatchDecision

class ReviewerGui(wx.Dialog):
    def __init__(self, log: logging.Logger) -> None:
        self.df: pandas.DataFrame = None
        self.__config: ConfigParser = None
        self.__control_row: int = 0
        self.__text_controls: dict = {}
        self.__image_directory: str = None
        self.__left_button: wx.Button = None
        self.__log: logging.Logger = None
        self.__my_grid: wx.GridBagSizer = None
        self.__my_panel: wx.Panel = None
        self.__progress_gauge: wx.Gauge = None
        self.__progress_text: wx.StaticText = None
        self.__radio_box: wx.RadioBox = None
        self.__right_button: wx.Button = None
        self.__row: int = 0
        self.__save_button: wx.Button = None

    def __add_comparison_row(self, data_field: str) -> None: ...
    def __add_decision_buttons(self) -> None: ...
    def __add_decision_radiobuttons(self) -> None: ...
    def __add_header_row(self) -> None: ...
    def __add_load_button(self) -> None: ...
    def __add_navigation_buttons(self) -> None: ...
    def __add_progress_info(self) -> None: ...
    def __add_save_and_cancel_buttons(self) -> None: ...
    def __add_single_info(self, data_field: str) -> None: ...
    def __add_title(self, label: str) -> None: ...
    def __build_row(self, data_field: str) -> tuple[wx.Panel, wx.GridBagSizer]: ...
    def __enable_upon_load(self) -> None: ...
    def __go_to_next_record(self) -> None: ...
    @staticmethod
    def __map_score_to_color(score: str) -> wx.Colour: ...
    def __on_box_select(self, event: wx.CommandEvent) -> None: ...
    def __on_cancel(self, event: wx.CloseEvent) -> None: ...
    def __on_close(self, event: wx.CloseEvent) -> None: ...
    def __on_go_left(self, event: wx.CloseEvent) -> None: ...
    def __on_go_right(self, event: wx.CloseEvent) -> None: ...
    def __on_load_file(self, event: wx.CommandEvent) -> None: ...
    def __on_match(self, event: wx.CommandEvent) -> None: ...
    def __on_meh(self, event: wx.CommandEvent) -> None: ...
    def __on_no_match(self, event: wx.CommandEvent) -> None: ...
    def __on_save(self, event: wx.CloseEvent) -> None: ...
    def __populate_data(self) -> None: ...
    def __read_classification(self) -> MatchDecision: ...
    def __set_radiobuttons(self) -> None: ...
    def __shade_row_based_on_score(self, score_label: wx.StaticText) -> None: ...
    def __update_progress(self) -> None: ...
